config/routes.rb
ClassAlert::Application.routes.draw do
  resources :school_users

  resources :schools

  devise_for :users

  root 'home#index'

end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :school_users
	has_many :users
end

app/models/school_user.rb
class SchoolUser < ActiveRecord::Base
	belongs_to :user
	belongs_to :school
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :school
  has_one :school_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/school_users_controller.rb
class SchoolUsersController < ApplicationController
  before_action :set_school_user, only: [:show, :edit, :update, :destroy]

  # GET /school_users
  # GET /school_users.json
  def index
    @school_users = SchoolUser.all
  end

  # GET /school_users/1
  # GET /school_users/1.json
  def show
  end

  # GET /school_users/new
  def new
    @school_user = SchoolUser.new
  end

  # GET /school_users/1/edit
  def edit
  end

  # POST /school_users
  # POST /school_users.json
  def create
    @school_user = SchoolUser.new(school_user_params)

    respond_to do |format|
      if @school_user.save
        format.html { redirect_to @school_user, notice: 'School user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @school_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @school_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /school_users/1
  # PATCH/PUT /school_users/1.json
  def update
    respond_to do |format|
      if @school_user.update(school_user_params)
        format.html { redirect_to @school_user, notice: 'School user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @school_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_users/1
  # DELETE /school_users/1.json
  def destroy
    @school_user.destroy
    respond_to do |format|
      format.html { redirect_to school_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_user
      @school_user = SchoolUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_user_params
      params[:school_user]
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render action: 'show', status: :created, location: @school }
      else
        format.html { render action: 'new' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :email_suffix)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/school_users_helper.rb
module SchoolUsersHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/home/index.html.erb
<% content_for :head do %>
<meta keywords="Class Alert"/>
<% end %>

<body>
<div class="fixed">
	<nav class="top-bar" data-topbar>
		<ul class="title-area">
			<li class="name">
			<h1><a href="#">Class Alert</a></h1>
			</li>
			<li class="toggle-topbar menu-icon">
				<a href="#">Menu</a>
			</li>
		</ul>

		<section class="top-bar-section">
		<!-- Right Nav Section -->
			<ul class="right">
			<li>
				<a href-"#">About ClassAlert</a></li>
			<% if user_signed_in? %>
			<% else %>
				<li>
					<a href="users/sign_up">Sign Up</a>
				</li>
			<% end %>
			<% if user_signed_in? %>
				<li class="has-dropdown">
					<a><%= current_user.email %></a>
					<ul class="dropdown">
						<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
					</ul>
				</li>
			<% else %>
				<li>
				<%= link_to('Login', new_user_session_path)  %>
				</li>
			<% end %>
			<!--
			<li class="has-dropdown">
				<a href="#">Right Button with Dropdown</a>
				<ul class="dropdown">
					<li><a href="#">First link in dropdown</a></li>
				</ul>
			</li>
			-->
			</ul>
		<!-- Left Nav Section
			<ul class="left">
				<li><a href="#">Left Nav Button</a></li>
			</ul>
			-->
		</section>
	</nav>
</div>

<div class="hero">
	<div class="panel center">
		<h1 class="text-center">Class Alert</h1>
		 <p class="text-center"><i>Why shouldn't you get the best education for your money?</i>
― Mark Twain</p>
	</div>
	<% if user_signed_in? %>
	<div>
		<h1 class="text-center"><%= current_user.school_user.school.name %></h1>
	</div>
	<% end %>
</div>

<div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/school_users/_form.html.erb
<%= form_for(@school_user) do |f| %>
  <% if @school_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school_user.errors.count, "error") %> prohibited this school_user from being saved:</h2>

      <ul>
      <% @school_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/school_users/edit.html.erb
<h1>Editing school_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @school_user %> |
<%= link_to 'Back', school_users_path %>

app/views/school_users/index.html.erb
<h1>Listing school_users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @school_users.each do |school_user| %>
      <tr>
        <td><%= link_to 'Show', school_user %></td>
        <td><%= link_to 'Edit', edit_school_user_path(school_user) %></td>
        <td><%= link_to 'Destroy', school_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School user', new_school_user_path %>

app/views/school_users/new.html.erb
<h1>New school_user</h1>

<%= render 'form' %>

<%= link_to 'Back', school_users_path %>

app/views/school_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_school_user_path(@school_user) %> |
<%= link_to 'Back', school_users_path %>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email_suffix %><br>
    <%= f.text_field :email_suffix %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email suffix</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.email_suffix %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Email suffix:</strong>
  <%= @school.email_suffix %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>